# Generated by Django 3.2.6 on 2021-10-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pic',
            field=models.ImageField(null=True, upload_to='pic'),
        ),
    ]
