# Generated by Django 3.2.6 on 2021-10-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_candidate_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
